### PR TITLE
completely rewriting the application

### PR DESCRIPTION
**Pull request by corpix**
Adding:

 - explicit rewrites for package urls
 - parser from go

Initially I have modified `vgo2nix` to be able to package fresh `bingo`(language server protocol agent for go) because it uses [git.apache.org/thrift.git](https://git.apache.org/thrift.git) and `vgo2nix` started to ask for a password(because `.git` was droped and `nix-prefetch-git` thinked it should use SSH to pull the repo).
But this was two months ago. After that I have packaged a lot of other software and have some pain with go pseudo versions. After that I have found [internal implementation](https://github.com/golang/go/blob/d346a9b7725b5313ddda3913cbcd5ff5fba0c909/src/cmd/go/internal/modfetch/pseudo.go) which go tools use and adopted it(internal packages can not be imported).

Also I have checked today, this fixed https://github.com/adisbladis/vgo2nix/issues/16
UPD: Oops this is because I dropped support for parallel jobs, lol, I'll bring them back soon

### CODE REVIEW

**Comment by corpix** [comment]
To c4609f4e3ee0fd010d80c471f6a67c56c2279ead: `test_reporoot/go.mod` declares two packages, so I have decided to fix the expected test result.

**Comment by dingxiangfei2009** [comment]
@corpix I have tried the rewritten version of yours. The usability of the rewritten `vgo2nix` is not so good because `prefetchModule` is a blocking process and dependencies are being downloaded sequentially instead of in parallel.

**Comment by corpix** [comment]
Oh, yeah, it is not good at parallel fetching at the moment. I think I'll fix this soon

**Comment by adisbladis** [comment]
I'd like to incorporate some of these changes but a massive rewrite PR is not helpful.
Please do smaller incremental pull requests that can be reviewed on their own merit.

**Comment by corpix** [comment]
Not sure I'll have enough time to do this, but anyway, feel free to incorporate any changes without listing me as contributor

**Pull request closed without merging**
